<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="90367" started-at="2018-02-27T11:54:03Z" finished-at="2018-02-27T11:55:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="90367" started-at="2018-02-27T11:54:03Z" finished-at="2018-02-27T11:55:34Z">
      <class name="test.horoscope.Total_horoscope">
        <test-method status="PASS" signature="appLaunch()[pri:0, instance:test.horoscope.Total_horoscope@29ca901e]" name="appLaunch" is-config="true" duration-ms="37236" started-at="2018-02-27T17:24:03Z" finished-at="2018-02-27T17:24:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- appLaunch -->
        <test-method status="FAIL" signature="performingRechargeApp()[pri:1, instance:test.horoscope.Total_horoscope@29ca901e]" name="performingRechargeApp" duration-ms="53105" started-at="2018-02-27T17:24:41Z" description="performing the Recharge" finished-at="2018-02-27T17:25:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Recharge successful] but found [Recharge failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Recharge successful] but found [Recharge failed]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.horoscope.util.Horoscope_baseLib.performingRecharge(Horoscope_baseLib.java:648)
	at test.horoscope.Total_horoscope.performingRechargeApp(Total_horoscope.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performingRechargeApp -->
      </class> <!-- test.horoscope.Total_horoscope -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
